version: '3.8'

services:
  madrid-housing-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    command: ["python", "src/api.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

