# Training configuration for Madrid Housing Market price prediction

# Data configuration
data:
  source_path: "houses_Madrid.csv"
  target_column: "buy_price"
  test_size: 0.2
  val_size: 0.2  # 20% of remaining data for validation
  random_state: 42

# MLflow configuration
mlflow:
  experiment_name: "housing_price_experiments"
  tracking_uri: "./mlruns"

# Default model configuration (used when running single experiment)
model:
  objective: "regression"
  metric: "rmse"
  boosting_type: "gbdt"
  n_estimators: 300
  min_child_samples: 4
  max_depth: 8
  num_leaves: 20
  learning_rate: 0.1
  feature_fraction: 0.9
  bagging_fraction: 0.8
  bagging_freq: 5
  verbose: -1
  random_state: 42

# Default training configuration
training:
  early_stopping_rounds: 10
  eval_metric: "rmse"
  verbose_eval: 100

# Multiple experimental runs with different configurations
experiments:
  - run_name: "baseline_model"
    description: "Baseline LightGBM with default parameters"
    model:
      objective: "regression"
      metric: "rmse"
      boosting_type: "gbdt"
      n_estimators: 500
      num_leaves: 31
      learning_rate: 0.1
      feature_fraction: 0.9
      bagging_fraction: 0.8
      bagging_freq: 5
      verbose: -1
      random_state: 42
    training:
      early_stopping_rounds: 10
      eval_metric: "rmse"
      verbose_eval: 100

  - run_name: "tuned_model"
    description: "Tuned LightGBM with optimized hyperparameters"
    model:
      objective: "regression"
      metric: "rmse"
      boosting_type: "gbdt"
      n_estimators: 1000
      num_leaves: 21
      learning_rate: 0.05
      feature_fraction: 0.8
      bagging_fraction: 0.7
      bagging_freq: 10
      min_data_in_leaf: 20
      min_sum_hessian_in_leaf: 1e-3
      lambda_l1: 0.1
      lambda_l2: 0.1
      verbose: -1
      random_state: 42
    training:
      early_stopping_rounds: 20
      eval_metric: "rmse"
      verbose_eval: 100

  - run_name: "high_performance_model"
    description: "High performance LightGBM with aggressive tuning"
    model:
      objective: "regression"
      metric: "rmse"
      boosting_type: "gbdt"
      n_estimators: 1500
      num_leaves: 50
      max_depth: 12
      learning_rate: 0.03
      feature_fraction: 0.7
      bagging_fraction: 0.6
      bagging_freq: 15
      min_data_in_leaf: 10
      min_sum_hessian_in_leaf: 1e-4
      lambda_l1: 0.2
      lambda_l2: 0.2
      max_depth: 8
      verbose: -1
      random_state: 42
    training:
      early_stopping_rounds: 30
      eval_metric: "rmse"
      verbose_eval: 50

# Grid search configuration
grid_search:
  enabled: true
  parameters:
    learning_rate: [0.05, 0.1, 0.15]
    num_leaves: [31, 50, 100]
    max_depth: [6, 8, 10]
    feature_fraction: [0.8, 0.9, 1.0]
  cv_folds: 3
  scoring: "neg_mean_squared_error"

# Model saving
model_saving:
  model_path: "models/madrid_housing_model.pkl"
